apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.devmysqldb.name }}
  labels: 
    group: {{ .Values.devmysqldb.group }}
spec:
  type: {{ .Values.devmysqldb.service.type }}
  selector:             
    app: {{ .Values.devmysqldb.name }}
  ports:
    - port: {{ .Values.devmysqldb.service.port }}       
      targetPort: {{ .Values.devmysqldb.container.port }}
