apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.devwebapps.name }}
  namespace: {{ .Values.devwebapps.namespace }}
  labels: 
    group: {{ .Values.devwebapps.group }}
spec:
  type: {{ .Values.devwebapps.service.type }}
  selector:             
    app: {{ .Values.devwebapps.name }}
  ports:
    - port: {{ .Values.devwebapps.service.port }}       
      targetPort: {{ .Values.devwebapps.container.port }}    
